#!/usr/bin/env bash
# A script that pings an IP address passed as an argument.
# Accepts a string as an argument and displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} is no argument is passed.
if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi
IP_ADDRESS=$1
ping -c 5 "$IP_ADDRESS"